name: build

on:
  push

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.11' 
    - name: ci-test
      run: make ci-test
    - name: set up QEMU
      uses: docker/setup-qemu-action@1
    - name: set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@1
    - name: login to GHCR
      uses: docker/login-action@1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker metadata
      id: dockermetadata
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/j-fuentes/multimedia-sync
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.dockermetadata.outputs.tags }}
        labels: ${{ steps.dockermetadata.outputs.labels }}
